notifications:
  email:
    recipients:
      - aurelien.grifasi@gmail.com
language: objective-c  #1
osx_image: xcode8 #2
xcode_project: AGNavigationBarShape.xcodeproj #3
xcode_scheme: AGNavigationBarShape-Example #4
script: xctool -project AGNavigationBarShape.xcodeproj -scheme AGNavigationBarShape-Example build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
