notifications:
  email:
    recipients:
      - aurelien.grifasi@gmail.com
language: objective-c  #1
osx_image: xcode8 #2
xcode_project: AGNavigationBarShape.xcworkspace #3
xcode_scheme: AGNavigationBarShape-Example #4
script:
  - xcodebuild -workspace ./Example/AGNavigationBarShape.xcworkspace -scheme AGNavigationBarShape-Example build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - pod lib lint
